fix-12

diff --git a/contrib/snap/snapcraft.yaml b/contrib/snap/snapcraft.yaml
--- a/contrib/snap/snapcraft.yaml
+++ b/contrib/snap/snapcraft.yaml
@@ -1,9 +1,9 @@
-name: pepecoin
+name: bonkcoin
 # Running 'snapcraft register <name>' is advised
 version: '1.1.0'
-summary: Reference client of Pepecoin, a peer-to-peer digital currency like Bitcoin.
+summary: Reference client of Bonkcoin, a peer-to-peer digital currency like Bitcoin.
 description: |
-  Pepecoin is a community-driven cryptocurrency that was inspired by Dogecoin. The Pepecoin Core software allows anyone to operate a node in the Pepecoin blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.
+  Bonkcoin is a community-driven cryptocurrency that was inspired by Dogecoin. The Bonkcoin Core software allows anyone to operate a node in the Bonkcoin blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.
 
 grade: stable
 confinement: strict
@@ -19,30 +19,30 @@ architectures:
 
 apps:
   d:
-    command: bin/pepecoind
+    command: bin/bonkcoind
     plugs: [home, removable-media, network, network-bind]
     environment:
-      # Override HOME so the datadir is located at ~/snap/pepecoin-core/common/.pepecoin/ instead of ~/snap/pepecoin-core/current/.pepecoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
+      # Override HOME so the datadir is located at ~/snap/bonkcoin-core/common/.bonkcoin/ instead of ~/snap/bonkcoin-core/current/.bonkcoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
       HOME: $SNAP_USER_COMMON
   qt:
     command-chain: [bin/desktop-launch]
-    command: bin/pepecoin-qt
+    command: bin/bonkcoin-qt
     plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
     environment:
       HOME: $SNAP_USER_COMMON
       DISABLE_WAYLAND: 1
   cli:
-    command: bin/pepecoin-cli
+    command: bin/bonkcoin-cli
     plugs: [home, removable-media, network]
     environment:
       HOME: $SNAP_USER_COMMON
   tx:
-    command: bin/pepecoin-tx
+    command: bin/bonkcoin-tx
     plugs: [home, removable-media, network]
     environment:
       HOME: $SNAP_USER_COMMON
   test:
-    command: bin/test_pepecoin
+    command: bin/test_bonkcoin
     plugs: [home, removable-media, network]
     environment:
       HOME: $SNAP_USER_COMMON
@@ -77,48 +77,48 @@ parts:
       - xdg-user-dirs
       - fcitx-frontend-qt5
 
-  pepecoin:
+  bonkcoin:
     plugin: nil
     override-build: |
-      echo "This script is viewable at https://github.com/pepecoinppc/pepecoin/blob/master/contrib/snap/snapcraft.yaml"
+      echo "This script is viewable at https://github.com/bonkcoinppc/bonkcoin/blob/master/contrib/snap/snapcraft.yaml"
       echo "Downloading files..."
-      if [ "$CRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but pepecoin designates it as i686
+      if [ "$CRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but bonkcoin designates it as i686
         BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
       else
         BUILD_ARCH_TRIPLET=$CRAFT_ARCH_TRIPLET
       fi
-      wget https://github.com/pepecoinppc/pepecoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/pepecoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
-      wget https://github.com/pepecoinppc/gitian.sigs/archive/refs/heads/master.tar.gz
+      wget https://github.com/bonkcoinppc/bonkcoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/bonkcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
+      wget https://github.com/bonkcoinppc/gitian.sigs/archive/refs/heads/master.tar.gz
       tar -xvf master.tar.gz
       echo "Verifying secure hash matches signed values..."
-      checksum=$(sha256sum pepecoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
-      if ! (grep -r $checksum * | grep pepecoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
+      checksum=$(sha256sum bonkcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
+      if ! (grep -r $checksum * | grep bonkcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
         echo "Secure hash not verified."
         return
       else
         echo "Secure hash verified."
       fi
-      tar -xvf pepecoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
+      tar -xvf bonkcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
       echo "Running tests..."
-      if ! (pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_pepecoin); then
-        echo "Pepecoin tests failed."
+      if ! (bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_bonkcoin); then
+        echo "Bonkcoin tests failed."
         return
       else
-        echo "Pepecoin tests passed."
+        echo "Bonkcoin tests passed."
       fi
-      wget https://raw.githubusercontent.com/pepecoinppc/pepecoin/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
+      wget https://raw.githubusercontent.com/bonkcoinppc/bonkcoin/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
       cat release-notes.md
-      echo "Installing Pepecoin Core..."
+      echo "Installing Bonkcoin Core..."
       echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
-      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pepecoind
-      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official pepecoin-qt build on arm64
-        install -m 0755 -D -t $CRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pepecoin-qt
+      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/bonkcoind
+      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official bonkcoin-qt build on arm64
+        install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/bonkcoin-qt
       fi
-      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pepecoin-cli
-      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pepecoin-tx
-      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_pepecoin
-      wget https://raw.githubusercontent.com/pepecoinppc/pepecoin/master/share/pixmaps/pepecoin128.png
-      install -m 0644 -D -t $CRAFT_PART_INSTALL/share/pixmaps pepecoin128.png
+      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/bonkcoin-cli
+      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/bonkcoin-tx
+      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_bonkcoin
+      wget https://raw.githubusercontent.com/bonkcoinppc/bonkcoin/master/share/pixmaps/bonkcoin128.png
+      install -m 0644 -D -t $CRAFT_PART_INSTALL/share/pixmaps bonkcoin128.png
     build-packages:
       - wget
     after:
